/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package epic.play;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author blanc
 */
public class CadastroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroUsuario
     */
    String status_situacao;
    
    
    String id_usuario;
    public CadastroUsuario() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        senha = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btListar = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusL = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        id.setEnabled(false);

        jLabel1.setText("Id Usuário:");

        jLabel2.setText("Nome de Usuário:");

        jLabel3.setText("Email:");

        jLabel4.setText("Senha");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Usuário", "Nome de Usuário", "Email", "Senha", "Status"
            }
        ));
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        btListar.setBackground(new java.awt.Color(153, 0, 0));
        btListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar");
        btListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListarMouseClicked(evt);
            }
        });

        btCadastrar.setBackground(new java.awt.Color(153, 0, 0));
        btCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrar.setText("cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(153, 0, 0));
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(153, 0, 0));
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_menu_planos.png"))); // NOI18N

        jLabel7.setText("Status");

        statusL.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome)
                            .addComponent(email)
                            .addComponent(senha)
                            .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusL, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(statusL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4)))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListarMouseClicked
        try {
              DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM usuario ORDER BY id_usuario";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            DebugLoggerSwing.log("Listando Usuarios");
            while(rs.next()){
                Object [] dados = {rs.getString("id_usuario"),rs.getString("nome"),rs.getString("email"),
                rs.getString("senha"),rs.getString("statusL")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            DebugLoggerSwing.log("Listando Usuarios Bem Sucessido");
            
        } catch (SQLException ex) {
            DebugLoggerSwing.log("Erro ao Listar Todos" );
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado em Lista", ex);
        };
    }//GEN-LAST:event_btListarMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        id.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        nome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        email.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        senha.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        statusL.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        try {
            DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "INSERT INTO usuario(nome,email,senha,statusL)VALUES(?,?,?,?);";
            System.out.println("Comecou a cadastrar 2");
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nome.getText());
            DebugLoggerSwing.log("Inicando Cadastro do Usuario Nome" + nome);
            stmt.setString(2, email.getText());
                DebugLoggerSwing.log("Inicando Cadastro do Usuario Email" + email );
            stmt.setString(3, senha.getText());
             DebugLoggerSwing.log("Inicando Cadastro do Usuario Senha" + senha );
             stmt.setString(4, statusL.getText());
               DebugLoggerSwing.log("Alterando Status" + statusL);
             stmt.execute();
         
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso!!!");
            nome.setText(null);
            email.setText(null);
            senha.setText(null);
            statusL.setText(null);
            id.setText(null);

        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado em cadastra", ex);
        }
        try {
             DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM usuario ORDER BY id_usuario";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_usuario"),rs.getString("nome"),rs.getString("email"),
                    rs.getString("senha"),rs.getString("statusL")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado Cadastra", ex);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        // TODO add your handling code here:
        int confirmacao = JOptionPane.showConfirmDialog(null,"Tem certeza?" , "confirmaçao de exclusao", JOptionPane.YES_NO_OPTION);
        
        if(confirmacao != JOptionPane.YES_NO_OPTION) {
        return;
        }
        
        try {
             DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "DELETE FROM usuario WHERE id_usuario = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, id_usuario);
            DebugLoggerSwing.log("Excluindo Usuario" + id_usuario);
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Usuário Excluido com Sucesso!!!");
             DebugLoggerSwing.log("Iniciando Exclusao");
            id.setText(null);
            nome.setText(null);
            email.setText(null);
            senha.setText(null);
       

        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado Excluir", ex);
        }
        try {
            DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM usuario ORDER BY id_usuario";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DebugLoggerSwing.log("Buscando usuario");
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_usuario"),rs.getString("nome"),rs.getString("email"),
                    rs.getString("senha"),rs.getString("statusL")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado Excluir", ex);
        }    
    }//GEN-LAST:event_btExcluirMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
 try {
            DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "UPDATE usuario SET nome = ?,email = ?,senha = ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nome.getText());
              DebugLoggerSwing.log("Alterando nome " + nome);
            stmt.setString(2, email.getText());
               DebugLoggerSwing.log("Alterando email" + email);
            stmt.setString(3, senha.getText());
               DebugLoggerSwing.log("Alterando senha" + senha);
            
           
 
            stmt.executeUpdate();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Usuário Alterado com Sucesso!!!");
            nome.setText(null);
            email.setText(null);
            senha.setText(null);
          
        
   
      
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
              DebugLoggerSwing.log("Erro encontrado Alterar", ex);
        }
        try {
            DebugLoggerSwing.log("Conectando com o banco de dados");
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM usuario ORDER BY id_usuario";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_usuario"),rs.getString("nome"),rs.getString("email"),
                rs.getString("senha"),rs.getString("statusL")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
             DebugLoggerSwing.log("Erro encontrado alterar", ex);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField senha;
    private javax.swing.JTextField statusL;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
