/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package epic.play;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author blanc
 */
public class CadastroJogos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroJogos
     */
    
    String id_jogos;
    String lancamentoDate;
    public CadastroJogos() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        desenvolvedor = new javax.swing.JTextField();
        plataforma = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lancamento = new org.netbeans.modules.form.InvalidComponent();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        classificacao = new javax.swing.JTextField();
        btCadastro = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel7.setText("Desenvolvedor:");

        jLabel8.setText("Plataforma:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Jogo", "Nome do Jogo", "Classificação", "Preço", "Gênero", "Data de Lançamento", "Desenvolvedor", "Plataforma", "Status"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        id.setEnabled(false);

        jLabel1.setText("Id Jogo:");

        jLabel2.setText("Nome do Jogo:");

        jLabel3.setText("Classificação:");

        jLabel4.setText("Preço");

        jLabel5.setText("Data de Lançamento:");

        jLabel6.setText("Gênero:");

        btCadastro.setBackground(new java.awt.Color(51, 51, 255));
        btCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btCadastro.setText("Cadastro do jogo");
        btCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastroMouseClicked(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(51, 51, 255));
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponivel", "Indisponivel" }));

        jLabel9.setText("Status:");

        btListar.setBackground(new java.awt.Color(51, 51, 255));
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar");
        btListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListarMouseClicked(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(51, 51, 255));
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(preco)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(classificacao))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(desenvolvedor)
                                            .addComponent(plataforma)
                                            .addComponent(genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(lancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(classificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desenvolvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastroMouseClicked
        SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-MM-dd");
        String data = dataFormatada.format(lancamento.getDate());
        
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "INSERT INTO Jogos(nome_jogo,classificacao,preco,genero,data_lancamento,"
                    + "desenvolvedor,plataformas,status)VALUES(?,?,?,?,?,?,?,?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nome.getText());
            stmt.setString(2, classificacao.getText());
            stmt.setString(3, preco.getText());
            stmt.setString(4, genero.getText());
            stmt.setString(5, data);
            stmt.setString(6, desenvolvedor.getText());
            stmt.setString(7, plataforma.getText());
            stmt.setString(8, status.getSelectedItem().toString());
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "jogo Cadastro com Sucesso!!!");
            nome.setText(null);
            classificacao.setText(null);
            preco.setText(null);
            genero.setText(null);
            lancamento.setDate(null);
            desenvolvedor.setText(null);
            plataforma.setText(null);
            status.setSelectedItem("Disponivel");
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Jogos ORDER BY id_jogos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_jogos"),rs.getString("nome_jogo"),rs.getString("classificacao"),
                rs.getString("preco"),rs.getString("genero"),rs.getString("data_lancamento"),rs.getString("desenvolvedor"),
                rs.getString("plataformas"),rs.getString("status")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btCadastroMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        id_jogos = (tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        nome.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        classificacao.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        preco.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        genero.setText(tabela.getValueAt(tabela.getSelectedRow(),4).toString());
        lancamentoDate = (tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        try{
            SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-mm-dd");
            Date dataLancamento = dataFormatada.parse(lancamentoDate);
            lancamento.setDate(dataLancamento);
        }catch(Exception e){
            e.printStackTrace();
        }
        desenvolvedor.setText(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        plataforma.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
        status.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
     try {
            Connection con = Conexao.conexaoBanco();
            String sql = "DELETE FROM Jogos WHERE id_jogos = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, id_jogos);
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Jogo Excluido com Sucesso!!!");
            nome.setText(null);
            classificacao.setText(null);
            preco.setText(null);
            genero.setText(null);
            lancamento.setDate(null);
            desenvolvedor.setText(null);
            plataforma.setText(null);
            status.setSelectedItem("Disponivel");            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
     try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Jogos ORDER BY id_jogos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_jogos"),rs.getString("nome_jogo"),rs.getString("classificacao"),
                rs.getString("preco"),rs.getString("genero"),rs.getString("data_lancamento"),rs.getString("desenvolvedor"),
                rs.getString("plataformas"),rs.getString("status")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void btListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Jogos ORDER BY id_jogos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_jogos"),rs.getString("nome_jogo"),rs.getString("classificacao"),
                rs.getString("preco"),rs.getString("genero"),rs.getString("data_lancamento"),rs.getString("desenvolvedor"),
                rs.getString("plataformas"),rs.getString("status")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btListarMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
       SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-MM-dd");
        String data = dataFormatada.format(lancamento.getDate());
        
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "UPDATE Jogos SET nome_jogo = ?,classificacao = ?,preco = ?,genero = ?,data_lancamento = ?,"
                    + "desenvolvedor = ?,plataformas = ?,status = ? WHERE id_jogos = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, nome.getText());
            stmt.setString(2, classificacao.getText());
            stmt.setString(3, preco.getText());
            stmt.setString(4, genero.getText());
            stmt.setString(5, data);
            stmt.setString(6, desenvolvedor.getText());
            stmt.setString(7, plataforma.getText());
            stmt.setString(8, status.getSelectedItem().toString());
            stmt.setString(9, id_jogos);
            stmt.executeUpdate();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Usuário Alterado com Sucesso!!!");
            nome.setText(null);
            classificacao.setText(null);
            preco.setText(null);
            genero.setText(null);
            lancamento.setDate(null);
            desenvolvedor.setText(null);
            plataforma.setText(null);
            status.setSelectedItem("Disponivel");
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Jogos ORDER BY id_jogos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_jogos"),rs.getString("nome_jogo"),rs.getString("classificacao"),
                rs.getString("preco"),rs.getString("genero"),rs.getString("data_lancamento"),rs.getString("desenvolvedor"),
                rs.getString("plataformas"),rs.getString("status")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroJogos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JTextField classificacao;
    private javax.swing.JTextField desenvolvedor;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.netbeans.modules.form.InvalidComponent lancamento;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField plataforma;
    private javax.swing.JTextField preco;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
