/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package epic.play;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author blanc
 */
public class CadastroTransacoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTransacoes
     */
    String id_transacao;
    String transacaoData;
    public CadastroTransacoes() {
        initComponents();
         try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM transacoes ORDER BY id_transacao";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_transacao"),rs.getString("quantidade"),rs.getString("valor"),
                rs.getString("data_transacao"),rs.getString("cupom_desconto"),rs.getString("metodo_pagamento"),rs.getString("status"),
                rs.getString("id_usuario"),rs.getString("id_jogos")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();
        quantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btAlterar = new javax.swing.JButton();
        valor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataTransacao = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cupom = new javax.swing.JTextField();
        pagamento = new javax.swing.JComboBox<>();
        estado = new javax.swing.JComboBox<>();
        idJogos = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel5.setText("Cupom de Desconto:");

        btListar.setBackground(new java.awt.Color(51, 51, 255));
        btListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar");
        btListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListarMouseClicked(evt);
            }
        });

        jLabel6.setText("Metodo de Pagamento:");

        btAlterar.setBackground(new java.awt.Color(51, 51, 255));
        btAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        jLabel7.setText("Status: ");

        btExcluir.setBackground(new java.awt.Color(51, 51, 255));
        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });

        jLabel8.setText("Id Usuário:");

        jLabel9.setText("Id Jogos:");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Transação", "Quantidade", "Valor", "Data da Transação", "Cupom de Desconto", "Metodo de Pagamento", "Status", "Id Usuário", "Id Jogos"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        id.setEnabled(false);

        jLabel1.setText("Id Transação:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor:");

        btCadastro.setBackground(new java.awt.Color(51, 51, 255));
        btCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btCadastro.setText("Cadastrar");
        btCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastroMouseClicked(evt);
            }
        });

        jLabel4.setText("Data da Transação:");

        pagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão de crédito", "Boleto bancário", "PIX" }));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprovado", "Rejeitado", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantidade)
                                    .addComponent(valor)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idUsuario)
                            .addComponent(cupom)
                            .addComponent(pagamento, 0, 216, Short.MAX_VALUE)
                            .addComponent(estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idJogos)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dataTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cupom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(idJogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM transacoes ORDER BY id_transacao";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_transacao"),rs.getString("quantidade"),rs.getString("valor"),
                rs.getString("data_transacao"),rs.getString("cupom_desconto"),rs.getString("metodo_pagamento"),rs.getString("status"),
                rs.getString("id_usuario"),rs.getString("id_jogos")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        SimpleDateFormat dataFormatada = new SimpleDateFormat("dd/MM/yyyy");
        String data = dataFormatada.format(dataTransacao.getDate());
    }//GEN-LAST:event_btListarMouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "DELETE FROM transacoes WHERE id_transacao = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, id_transacao);
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Transação Excluido com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);
            dataTransacao.setDate(null);
            cupom.setText(null);
            pagamento.setSelectedItem(null);
            estado.setSelectedItem(null);
            idUsuario.setText(null);
            idJogos.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM transacoes ORDER BY id_transacao";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_transacao"),rs.getString("quantidade"),rs.getString("valor"),
                rs.getString("data_transacao"),rs.getString("cupom_desconto"),rs.getString("metodo_pagamento"),rs.getString("status"),
                rs.getString("id_usuario"),rs.getString("id_jogos")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        id_transacao = (tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        quantidade.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        valor.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        transacaoData = (tabela.getValueAt(tabela.getSelectedRow(),3).toString());
        try{
            SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-mm-dd");
            Date dataRegistro = dataFormatada.parse(transacaoData);
            dataTransacao.setDate(dataRegistro);
        }catch (Exception e){
            e.printStackTrace();
        }
        cupom.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
        pagamento.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
        estado.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 6).toString());
        idUsuario.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
        idJogos.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());

    }//GEN-LAST:event_tabelaMouseClicked

    private void btCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastroMouseClicked
        SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-MM-dd");
        String data = dataFormatada.format(dataTransacao.getDate());
        
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "INSERT INTO transacoes(quantidade,valor,data_transacao,cupom_desconto,metodo_pagamento,status,id_usuario,id_jogos)VALUES(?,?,?,?,?,?,?,?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, quantidade.getText());
            stmt.setString(2, valor.getText());
            stmt.setString(3, data);
            stmt.setString(4, cupom.getText());
            stmt.setString(5, pagamento.getSelectedItem().toString());
            stmt.setString(6, estado.getSelectedItem().toString());
            stmt.setString(7, idUsuario.getText());
            stmt.setString(8, idJogos.getText());
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Transação Cadastrado com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);
            dataTransacao.setDate(null);
            cupom.setText(null);
            pagamento.setSelectedItem("Cartão de crédito");
            estado.setSelectedItem("Aprovado");
            idUsuario.setText(null);
            idJogos.setText(null);

        } catch (SQLException ex) {
            Logger.getLogger(CadastroPresente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM transacoes ORDER BY id_transacao";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_transacao"),rs.getString("quantidade"),rs.getString("valor"),
                rs.getString("data_transacao"),rs.getString("cupom_desconto"),rs.getString("metodo_pagamento"),rs.getString("status"),
                rs.getString("id_usuario"),rs.getString("id_jogos")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        

    }//GEN-LAST:event_btCadastroMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        SimpleDateFormat dataFormatada = new SimpleDateFormat("yyyy-MM-dd");
        String data = dataFormatada.format(dataTransacao.getDate());
        
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "UPDATE transacoes SET quantidade = ?,valor = ?,data_transacao = ?,cupom_desconto = ?,metodo_pagamento = ?,"
            + "status = ?,id_usuario = ?,id_jogos = ? WHERE id_transacao = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, quantidade.getText());
            stmt.setString(2, valor.getText());
            stmt.setString(3, data);
            stmt.setString(4, cupom.getText());
            stmt.setString(5, pagamento.getSelectedItem().toString());
            stmt.setString(6, estado.getSelectedItem().toString());
            stmt.setString(7, idUsuario.getText());
            stmt.setString(8, idJogos.getText());
            stmt.setString(9, id_transacao);
            stmt.executeUpdate();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Transação Alterado com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);
            dataTransacao.setDate(null);
            cupom.setText(null);
            pagamento.setSelectedItem(null);
            estado.setSelectedItem(null);
            idUsuario.setText(null);
            idJogos.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM transacoes ORDER BY id_transacao";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_transacao"),rs.getString("quantidade"),rs.getString("valor"),
                rs.getString("data_transacao"),rs.getString("cupom_desconto"),rs.getString("metodo_pagamento"),rs.getString("status"),
                rs.getString("id_usuario"),rs.getString("id_jogos")};
                tabelaModelo.addRow(dados);
                
            }
            stmt.close();
            rs.close();
            con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(CadastroTransacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

       
    }//GEN-LAST:event_btAlterarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JTextField cupom;
    private com.toedter.calendar.JDateChooser dataTransacao;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idJogos;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pagamento;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
