/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package epic.play;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy54053236
 */
public class CadastroAmigos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroAmigos
     */
    String id_amigos;
    public CadastroAmigos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();
        postagens = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        chat = new javax.swing.JTextField();
        grupos = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setText("Postagens:");

        jLabel3.setText("Chat:");

        btCadastro.setBackground(new java.awt.Color(51, 51, 255));
        btCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btCadastro.setText("Cadastrar");
        btCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastroMouseClicked(evt);
            }
        });

        jLabel4.setText("Grupos:");

        jLabel5.setText("Id Usuário:");

        btListar.setBackground(new java.awt.Color(51, 51, 255));
        btListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar");
        btListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListarMouseClicked(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(51, 51, 255));
        btAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(51, 51, 255));
        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Amigos", "Postagens", "Chat", "Grupos", "Id Usuário"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        id.setEnabled(false);

        jLabel1.setText("Id Amigos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(postagens)
                                    .addComponent(chat)
                                    .addComponent(grupos)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(123, 123, 123)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(313, 313, 313))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastroMouseClicked
           try {
            Connection con = Conexao.conexaoBanco();
            String sql = "INSERT INTO Amigos(postagens,chat,senha,grupos,id_usuario)VALUES(?,?,?,?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, postagens.getText());
            stmt.setString(2, chat.getText());
            stmt.setString(3, grupos.getText());
            stmt.setString(4, idUsuario.getText());
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Amigo Cadastro com Sucesso!!!");
            postagens.setText(null);
            chat.setText(null);
            grupos.setText(null);
            idUsuario.setText(null);

        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Amigos ORDER BY id_amigos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_amigos"),rs.getString("postagens"),rs.getString("chat"),
                    rs.getString("grupos"),rs.getString("id_usuario")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btCadastroMouseClicked

    private void btListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Amigos ORDER BY id_amigos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_amigos"),rs.getString("postagens"),rs.getString("chat"),
                    rs.getString("grupos"),rs.getString("id_usuario")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btListarMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "UPDATE Amigos SET postagens = ?,chat = ?,grupos = ?,id_usuario = ? WHERE id_cliente = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, postagens.getText());
            stmt.setString(2, chat.getText());
            stmt.setString(3, grupos.getText());
            stmt.setString(6, idUsuario.getText());
            stmt.executeUpdate();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Amigo Alterado com Sucesso!!!");
            postagens.setText(null);
            chat.setText(null);
            grupos.setText(null);
            idUsuario.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Amigos ORDER BY id_amigos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_amigos"),rs.getString("postagens"),rs.getString("chat"),
                    rs.getString("grupos"),rs.getString("id_usuario")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "DELETE FROM Amigos WHERE id_amigos = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, id_amigos);
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Amigo Excluido com Sucesso!!!");
            postagens.setText(null);
            chat.setText(null);
            grupos.setText(null);
            idUsuario.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM Amigos ORDER BY id_amigos";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_amigos"),rs.getString("postagens"),rs.getString("chat"),
                    rs.getString("grupos"),rs.getString("id_usuario")};
                tabelaModelo.addRow(dados);

            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroAmigos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        id_amigos = (tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        postagens.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        chat.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
        grupos.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
        idUsuario.setText(tabela.getValueAt(tabela.getSelectedRow(),4).toString());
        

    }//GEN-LAST:event_tabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JTextField chat;
    private javax.swing.JTextField grupos;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField postagens;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
