/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package epic.play;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author blanc
 */
public class CadastroLoja extends javax.swing.JInternalFrame {

    /** Creates new form CadastroLoja */
    
    String id_loja;
    public CadastroLoja() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCadastro = new javax.swing.JButton();
        quantidade = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        id = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Id Loja:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor:");

        btCadastro.setBackground(new java.awt.Color(51, 51, 255));
        btCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btCadastro.setText("Cadastrar");
        btCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadastroMouseClicked(evt);
            }
        });

        btAlterar.setBackground(new java.awt.Color(51, 51, 255));
        btAlterar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btAlterar.setText("Alterar");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });

        btExcluir.setBackground(new java.awt.Color(51, 51, 255));
        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btExcluir.setText("Excluir");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });

        btListar.setBackground(new java.awt.Color(51, 51, 255));
        btListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btListar.setForeground(new java.awt.Color(255, 255, 255));
        btListar.setText("Listar");
        btListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btListarMouseClicked(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Loja", "Quantidade", "Valor"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        id.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantidade)
                                    .addComponent(valor)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastroMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "INSERT INTO loja(quantidade,valor)VALUES(?,?);";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, quantidade.getText());
            stmt.setString(2, valor.getText());
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "O Item foi Cadastro com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);

        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM loja ORDER BY id_loja";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_loja"),rs.getString("quantidade"),rs.getString("valor")};
                tabelaModelo.addRow(dados);
            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btCadastroMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "UPDATE loja SET quantidade = ?,valor = ? WHERE id_loja = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, quantidade.getText());
            stmt.setString(2, valor.getText());
            stmt.setString(3, id_loja);
            stmt.executeUpdate();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Item Alterado com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM loja ORDER BY id_loja";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_loja"),rs.getString("quantidade"),rs.getString("valor")};
                tabelaModelo.addRow(dados);
            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "DELETE FROM loja WHERE id_loja = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, id_loja);
            stmt.execute();
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(null, "Item Excluido com Sucesso!!!");
            quantidade.setText(null);
            valor.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM loja ORDER BY id_loja";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_loja"),rs.getString("quantidade"),rs.getString("valor")};
                tabelaModelo.addRow(dados);
            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btExcluirMouseClicked

    private void btListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btListarMouseClicked
        try {
            Connection con = Conexao.conexaoBanco();
            String sql = "SELECT * FROM loja ORDER BY id_loja";
            PreparedStatement stmt = con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel tabelaModelo = (DefaultTableModel) tabela.getModel();
            tabelaModelo.setNumRows(0);
            while(rs.next()){
                Object [] dados = {rs.getString("id_loja"),rs.getString("quantidade"),rs.getString("valor")};
                tabelaModelo.addRow(dados);
            }
            stmt.close();
            rs.close();
            con.close();

        } catch (SQLException ex) {
            Logger.getLogger(CadastroLoja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btListarMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        id_loja = (tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
        quantidade.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
        valor.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());

    }//GEN-LAST:event_tabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables

}
